version: '3.8'

services:
  tak-server:
    image: ubuntu:22.04
    container_name: tak-server-ubuntu
    restart: unless-stopped
    ports:
      - "8445:8443"   # TAK Server Web Interface
      - "8092:8089"   # ATAK Client Port
      - "5433:5432"   # PostgreSQL Database
      - "8444:8444"   # Federation Port (optional)
      - "8446:8446"   # Certificate Management (optional)
    volumes:
      - ./appdata/tak-server:/setup
    environment:
      - TZ=America/New_York
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    command: >
      bash -c "
        echo 'TAK Server 5.4 Ubuntu Starting...' &&
        apt-get update -qq &&
        apt-get install -y git wget curl &&
        echo 'Downloading setup scripts...' &&
        git clone https://github.com/Zeroradiance/tak-server-unraid.git /tmp/taksetup &&
        cp -r /tmp/taksetup/scripts /setup/ &&
        cp /tmp/taksetup/CoreConfig.xml /setup/ &&
        cd /setup &&
        chmod +x scripts/setup-ubuntu.sh &&
        exec scripts/setup-ubuntu.sh
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8443"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 300s

networks:
  default:
    driver: bridge

volumes:
  tak-data:
    driver: local
